### PR TITLE
Merge remote-tracking branch 'origin/master' into dev

### PR DESCRIPTION
**Pull request by hang2loose**

### CODE REVIEW

**Review by SaveEnergy — COMMENTED** [review]
Your comments need to improve!

**Review by SaveEnergy — APPROVED** [review]
fine

**Comment by hang2loose** [comment]
> Your comments need to improve!

which comments ?

**Comment by SaveEnergy** [comment]
You didn't refactor the sorting view but fixed the lowerCase in our search parameter.

**Pull request merged**
